### ISSUE TITLE
v20.5.1 Doesnt boot

### ISSUE THREAD

**Issue by hdiass** [matter-labs/zksync-era#1001]
#### 📝 Description
After having issues with v20.1.0 i tried to update to v20.4.0 and it crashed.. then i updated to v20.5.1 and it doesn't even boot
External node image version v20.5.1 doesnt boot or throw any logs
#### 🔄 Reproduction Steps

Steps to reproduce the behaviour

#### 🤔 Expected Behavior

Start external node normally
#### 😯 Current Behavior

Gets stuck and doesn't throw any log
#### 🖥️ Environment

matterlabs/external-node:v20.5.1

#### 📋 Additional Context

Add any other context about the problem here. If applicable, add screenshots to help explain.

#### 📎 Log Output

```
Paste any relevant log output here.
```

**Comment by gathecageorge** [comment]
Same thing happened when we upgraded from 20.4.0 to 20.5.1, a table was deleted resulting in error log shown below and continuous restart. Creating the table and restarting node resolved the issue.

thread 'main' panicked at /usr/src/zksync/core/lib/dal/src/transactions_dal.rs:855:14:
called `Result::unwrap()` on an `Err` value: Database(PgDatabaseError { severity: Error, code: "42P01", message: "relation \"call_traces\" does not exist", detail: None, hint: None, position: Some(Original(30)), where: None, schema: None, table: None, column: None, data_type: None, constraint: None, file: Some("parse_relation.c"), line: Some(1449), routine: Some("parserOpenTable") })

create table call_traces
(
    tx_hash    bytea not null
        primary key
        references transactions
            on delete cascade,
    call_trace bytea not null
)

**Comment by sarkic20** [comment]
Great project

**Comment by raymonredington** [comment]
Interesting, I'll look at that

**Comment by Deniallugo** [comment]
@hdiass Thanks for the report. 
You have to run the latest possible version, now it's 20.5.2 and it's expected that boot time is higher, because we are performing relatively high migration at the start.

**Comment by hdiass** [comment]
I think there are some better ways to approach release management on this project too..in last 5 days there were 5 releases, can't they been joint together in one release ?

**Comment by patapata24** [comment]
Great project

**Comment by dzhamilrustamov** [comment]
describe your problem in more detail

**Comment by jcarlo-vs** [comment]
have u resolved this issue sir?
