### ISSUE TITLE
Remove one of two persistence locations for external-node

### ISSUE THREAD

**Issue by hdiass** [matter-labs/zksync-era#1009]
### 🌟 Feature Request
Use just PG as persistence layer for external node
#### 📝 Description
I'd like that all zksync state was stored on PG. Instead of having Filesystem+ PG.
Provide a clear and concise description of the feature you'd like to see.
I'd like that all zksync state was stored on PG. Instead of having Filesystem+ PG.

#### 🤔 Rationale
Having a backup of PG is not enough. FS+PG consistency is not resilient as if you rollback in PG and filesystem as a newer blocks it will break and require full filesystem sync.
There should be only one persistence layer.

Explain why this feature is important and how it benefits the project.
Having a backup of PG is not enough to guarantee state.
Did PITR in PG and broke the consistency between FS+PG which required me to resync entirely the Filesystem, which takes days.

#### 📋 Additional Context

Add any other context or information about the feature request here.

**Comment by popzxc** [comment]
RocksDB is used in performance-critical places (like state keeper cache and merkle tree), using them with postgres will be too slow.
At the same time, Postgres is a source of truth (e.g. RocksDB acts like a cache, so even at loss of RocksDB data, the server will be able to recover it; this will take a while, though).

So, both RocksDB and Postgres are used intentionally and I don't think it'll be feasible to get rid of any of them, at least for now.
