### ISSUE TITLE
Solidity verifier does not accept optimization mode

### ISSUE THREAD

**Issue by monokh** [matter-labs/zksync-era#1072]
#### 📝 Description

Calling the verifier api with a contract compiled using any optimization mode except "3" will not result in the correct compilation from the verifier. 

#### 🔄 Reproduction Steps

Compile a contract with zksolc optimizer mode "z"

Use hardhat verifier, manually or on explorer.

#### 🤔 Expected Behavior

Verifier should pass and verify the contract correctly

#### 😯 Current Behavior

Verifier errors: `Deployed bytecode is not equal to generated one from given source`

#### 🖥️ Environment

[Any relevant environment details.](https://zksync2-mainnet-explorer.zksync.io/contract_verification)

#### 📋 Additional Context

This seems to happen because for building the solc input, the verifier does not pass on `optimizerMode` like it does for the vyper input: 

https://github.com/matter-labs/zksync-era/blob/main/core/bin/contract-verifier/src/verifier.rs#L304

See implemented correctly for vyper: https://github.com/matter-labs/zksync-era/blob/main/core/bin/contract-verifier/src/verifier.rs#L304

#### 📎 Log Output

```
Error in plugin @matterlabs/hardhat-zksync-verify: Backend verification error: Deployed bytecode is not equal to generated one from given source

ZkSyncVerifyPluginError: Backend verification error: Deployed bytecode is not equal to generated one from given source
```

**Comment by hypenikkkkk** [comment]
let settings = Settings {
    libraries: None,
    output_selection: Some(default_output_selection),
    optimizer: Optimizer::new(request.req.optimization_used),
    is_system: request.req.is_system,
    metadata: None,
};

**Comment by perekopskiy** [comment]
Hi @monokh, thanks for raising it! This a bug indeed and I will prepare a fix soon, but it affects only `solidity-single-file` verification mode, while `solidity-standard-json` seems to be working correctly with optimizer modes. AFAIK, hardhat plugin uses only `solidity-standard-json` so you should be able to verify contract with non-default optimizer mode using plugin

**Comment by monokh** [comment]
> Hi @monokh, thanks for raising it! This a bug indeed and I will prepare a fix soon, but it affects only `solidity-single-file` verification mode, while `solidity-standard-json` seems to be working correctly with optimizer modes. AFAIK, hardhat plugin uses only `solidity-standard-json` so you should be able to verify contract with non-default optimizer mode using plugin

Thanks for looking into this
You are right, the hardhat plugin is using standard json input.
The way i found this issue is using single solidity file, especially on the zksync explorer and etherscan. 
The zksync explorer doesn't support standard json input and the etherscan explorer doesn't allow me to upload because the size of the input (3.2 MB) is above the allowed size (3MB) :/

Yet I am still unable to verify our contract, I have checked that the compiler versions match through the verification payload and build.json
Reproducable example here if you would like to try it: https://github.com/bebop-dex/bebop-jam-contracts?tab=readme-ov-file#deploying-to-zksync

**Comment by monokh** [comment]
I should also mention that our contract deploys another contract in the constructor 
Does this cause an issue with verification? I believe that i saw an issue somewhere about this

**Comment by perekopskiy** [comment]
Thanks, it should be enough to investigate, let me come back later after I try it

**Comment by monokh** [comment]
sorry had the mainnet adress wrong 😅  I've updated it - correct is `0x574d1fcF950eb48b11de5DF22A007703cbD2b129`

**Comment by perekopskiy** [comment]
@monokh we've found a problem in hardhat verification plugin. Problem was triggered because you are using hardhat-preproccesor plugin. For now please verify contracts compiled with this plugin with `no-compile` flag, i.e.`npx hardhat verify --no-compile ...`.
