### ISSUE TITLE
Unable to vendor crates

### ISSUE THREAD

**Issue by haraldh** [matter-labs/zksync-era#1086]
Using current commit `6d540100aeb3fa237cb23b2f1168d82f9d8e1930`:

```
❯ cargo vendor
error: failed to sync

Caused by:
  found duplicate version of package `bellman_ce v0.3.2` vendored from two sources:

  	source 1: https://github.com/matter-labs/bellman?branch=dev#5520aa22
  	source 2: https://github.com/matter-labs/bellman?branch=snark-wrapper#e01e5fa0
```

Also `cargo tree -d` finds **a lot** of duplicate dependencies.

**Comment by dzhamilrustamov** [comment]
describe your problem in more detail

**Comment by haraldh** [comment]
The whole dependency chain is a mess... packages are referred to with the same version and name but with a different git branch.
Ideally you could `cargo vendor` the repo to get a reproducible set of dependencies for a reproducible build.

**Comment by haraldh** [comment]
Recommendation: change the package name to `${orig}-${branchname}` in the repos in question, or change the version.

```
source = "git+https://github.com/matter-labs/franklin-crypto?branch=dev#5695d07c7bc604c2c39a27712ffac171d39ee1ed"
source = "git+https://github.com/matter-labs/franklin-crypto?branch=snark_wrapper#2546c63b91b59bdb0ad342d26f03fb57477550b2"

source = "git+https://github.com/matter-labs/bellman?branch=dev#5520aa2274afe73d281373c92b007a2ecdebfbea"
source = "git+https://github.com/matter-labs/bellman?branch=snark-wrapper#e01e5fa08a97a113e76ec8a69d06fe6cc2c82d17"
```

I'll file a bug against these repos.

**Comment by haraldh** [comment]
Found a PR, which enables `cargo vendor --no-merge-sources` , which solves the problem... https://github.com/rust-lang/cargo/pull/13271

**Comment by popzxc** [comment]
Hello! We are planning to get rid of `git` dependencies and publish everything on `crates.io`. 
With that, the problem should be resolved.

**Comment by haraldh** [comment]
> Hello! We are planning to get rid of `git` dependencies and publish everything on `crates.io`. With that, the problem should be resolved.

That would be the best solution ever :partying_face:

**Comment by joonazan** [comment]
The background here is that when the crypto team uses 1.4.1, that means protocol version 1.4.1. So pretty much as far from semver as you can be. The crates.io will at least force publishing different versions but we might consider enforcing semver.

**Comment by popzxc** [comment]
We will use a separate, semver-compliant versioning scheme for *crates* (e.g. let's say that `1.4.1` represents a "protocol" version, but all the crates will live in `0.x.y` domain).

**Comment by popzxc** [comment]
Up to @haraldh
