### ISSUE TITLE
contract-verifier Dockerfile - The script may not have permission to execute

### ISSUE THREAD

**Issue by yxc20086** [matter-labs/zksync-era#1089]
### 🐛 Bug Report
https://github.com/matter-labs/zksync-era/blame/main/docker/contract-verifier/Dockerfile#L33
#### 📝 Description
here no  chmod +x   possible may not have permission to execute
Provide a clear and concise description of the bug.

#### 🔄 Reproduction Steps

Steps to reproduce the behaviour

#### 🤔 Expected Behavior

Describe what you expected to happen.

#### 😯 Current Behavior

Describe what actually happened.

#### 🖥️ Environment

Any relevant environment details.

#### 📋 Additional Context

Add any other context about the problem here. If applicable, add screenshots to help explain.

#### 📎 Log Output

```
Paste any relevant log output here.
```

**Comment by jcarlo-vs** [comment]
nice catch there.
