### ISSUE TITLE
Official Marketplace for NFT 404 token

### ISSUE THREAD

**Issue by zerosecxz** [matter-labs/zksync-era#1118]
### 🌟 Feature Request

- Auto Wrap
- Official Partner
- Avoid Money Laundering 
- Untapped web2 market

#### 📝 Description

Wrap 404 its really amazing can potential bring a lot liq on network, its make easy create fraction nft 

#### 🤔 Rationale

so many scam nft with phising contract for nft on zk it automatically drain wallet

**Comment by DLTKauz** [comment]
Thx for this

**Comment by zerosecxz** [comment]
Your welcome
