### ISSUE TITLE
Deploy zkSync on Uniswap V2

### ISSUE THREAD

**Issue by AbduAlexander** [matter-labs/zksync-era#1120]
#### 📝 Description

I would be delighted to see zkSync network deployed on Uniswap V2, regardless of the current protocol OKU trade V3

#### 🤔 Rationale

I truly believe it will attract more users, the adoption will increase as it's a top Dex on Ethereum 

#### 📋 Additional Context

Add any other context or information about the feature request here.

**Comment by DLTKauz** [comment]
Its a must do, when finished?

**Comment by AbduAlexander** [comment]
Thanks for your response, issue already closed, keep the good work with our
zkSync devs community

#include <iostream>

int main() {

std::cout << "Much love for zksync devs << std::endl;

return 0;

}
