### ISSUE TITLE
Privacy-Preserving Borrowing/Lending

### ISSUE THREAD

**Issue by akuon** [matter-labs/zksync-era#1129]
**Description** : Develop privacy-preserving solutions for borrowing and lending protocols on zkSync Era, allowing users to participate without revealing their financial positions or transaction details.

**Rationale** : Privacy concerns are a major barrier to adoption for some users, especially with DeFi applications. Privacy-preserving borrowing/lending could attract new users and unlock additional use cases.

**Additional Context** : Explore different privacy-enhancing technologies (e.g., zero-knowledge proofs, homomorphic encryption) and their suitability for this specific application.

**Comment by Web3Certified** [comment]
to me FHE would have been the besst bet on this Privacy process, but the question is can FHE merge with Zksync so easily
.

**Comment by akuon** [comment]
> to me FHE would have been the besst bet on this Privacy process, but the question is can FHE merge with Zksync so easily .

While directly merging FHE with zkSync Era is currently not feasible, exploring hybrid solutions or targeted integrations for specific use cases holds promise for leveraging the benefits of both technologies.

**Comment by popzxc** [comment]
Not currently on a roadmap.
