### ISSUE TITLE
Native Multi-Signature Wallets

### ISSUE THREAD

**Issue by akuon** [matter-labs/zksync-era#1135]
**Description** :

This feature request proposes the implementation of native multi-signature wallets on the zkSync Era network. Multi-signature wallets require multiple private keys to authorize transactions, enhancing security and control over crypto assets. This feature would leverage the scalability and low transaction fees of zkSync Era, making it an attractive option for users seeking secure and efficient multi-party control over their funds.

**Rationale** :

- **Enhanced Security** : Multi-signature wallets distribute control over private keys, preventing unauthorized access even if one key is compromised. This is crucial for safeguarding valuable crypto assets.
- **Institutional Adoption** : Many institutions and investment firms require multi-signature wallets for compliance and security reasons. Native support on zkSync Era could attract these institutions to the network.
- **DAO and Community Management** : Multi-signature wallets are essential for DAOs and communities to manage shared funds securely and transparently. This feature would make zkSync Era more attractive for decentralized governance models.
- **Scalability and Efficiency** : zkSync Era's low transaction fees and fast confirmation times make it an ideal platform for multi-signature transactions, which can be complex and involve multiple parties.

**Additional Context** :

- Existing multi-signature solutions on zkSync Era often rely on smart contracts, which can be complex to manage and incur higher fees. Native support would streamline the process and improve user experience.
- Decentralized exchanges (DEXs) and other DeFi applications could benefit from native multi-signature wallets for secure escrow and custody of assets.
- Integration with existing multi-signature wallet solutions should be considered for a smooth user transition.

**Potential Benefits** :

+ Increased adoption of zkSync Era by institutions and individuals seeking secure multi-party control over their crypto assets.
+ Enhanced security and transparency for DAOs and communities managing shared funds.
+ Improved user experience and efficiency for multi-signature transactions.
+ Potential for new DeFi applications built around secure multi-signature functionalities.

**Comment by popzxc** [comment]
zkSync Era natively supports account abstraction, which means that even EOAs on zkSync Era are smart contracts. Anyone is able to implement their custom account, and it'd be natively supported.
