### ISSUE TITLE
zkhypercomics

### ISSUE THREAD

**Issue by CalebAduu** [matter-labs/zksync-era#1183]
Make Reduce gas UI feature more noticeable

📝 Description

claiming the hypercomics nfts i noticed gas is always high which led me to not want to claim at all until i realized there is a small info that says how to reduce gas, would be nice if the info UI was larger and more visible and noticeable

**Comment by jcarlo-vs** [comment]
zkhypercomics isn't related to zksync here itself. it's another 3rd party project. thanks.
