### ISSUE TITLE
Governance Token

### ISSUE THREAD

**Issue by mattpett** [matter-labs/zksync-era#1186]
#### 📝 Description

Governance Token

#### 🤔 Rationale

To further decentralize the network it would be prudent to create a governance token. In line with other protocols, ZkSync should consider airdropping said token to early users and contributors to the vibrant platform 🫡

**Comment by balala666888** [comment]
when

**Comment by LmingXie** [comment]
Where can I learn about the zkSync decentralized sequencer build process?
