### ISSUE TITLE
TRANSACTION FAILS  BY USING PAYMASTER 

### ISSUE THREAD

**Issue by irfand29** [matter-labs/zksync-era#1228]
#### 📝 Description
When attempting to execute transactions using the Paymaster feature with the HOLD token designated as the gas fee, I am  experiencing consistent failures , transactions are unable to proceed successfully.

#### 🤔 Rationale

This  enabling users to effortlessly execute transactions and explore various functionalities,  enhance user engagement
#### 📋 Additional Context

Add any other context or information about the feature request here.

**Comment by irfand29** [comment]
Again, continuously 3 transaction failures by using paymaster (HOLD,LIBERTAS token as gas fee) while adding liquidity .

**Comment by 0xAditya-eth** [comment]
Please ensure you have given access to use your desired gas token to the protocol you're using and you have sufficient funds to pay the gas

**Comment by cl3pl4t3** [comment]
could be a problem in one of the adress

**Comment by luksbit** [comment]
It happened to me too, but when I went to swap. but now it seems that it is no longer failing

**Comment by mosesshah** [comment]
could be a glitch, but it's working fine now

**Comment by pc1223** [comment]
I have also faced this issue multiple times

**Comment by bxpana** [comment]
@irfand29 or anyone else, if you're having this issue still can you please open a post in https://github.com/zkSync-Community-Hub/zkync-developers/discussions so we can get all the necessary information to check it out?

**Comment by StanislavBreadless** [comment]
Is this issue still relevant? If yes, which paymaster do you use?

**Comment by nirobAI** [comment]
> Is this issue still relevant? If yes, which paymaster do you use?

No it's not anymore. I had done 5+ transactions and it went smooth
