### ISSUE TITLE
eth_maxPriorityFeePerGas not available

### ISSUE THREAD

**Issue by LouisWT** [matter-labs/zksync-era#13]
While zkSync era using EIP1559,  eth_maxPriorityFeePerGas isn't implemented.
```
curl --url https://zksync2-mainnet.zksync.io \
-X POST \
-H "Content-Type: application/json" \
-d '{ "id": 1, "jsonrpc": "2.0", "method": "eth_maxPriorityFeePerGas" }'

{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":1}
```

Although eth_maxPriorityFeePerGas is not a standard rpc method of Ethereum, it is very important in practical use, especially for determining gas fee when sending transactions.

Thanks!

**Comment by hatemosphere** [comment]
@LouisWT zkSync Era does support the EIP-1559 transaction-type format which includes maxPriorityFeePerGas and maxFeePerGas parameters. However, it's important to note that zkSync Era does nothing with these max fee parameters. This means that while the transaction format is supported, the specific parameters related to maximum gas fees do not have any effect within the zkSync Era system.
so "method not found" might look a bit misleading, but correct in general

**Comment by popzxc** [comment]
Reopening this issue, as it's relevant outside from Era context: SDKs may expect this method to exist.
So, it should be implemented, but we should always return 0.
