### ISSUE TITLE
Too many farmers on github hoping to eat some form of big $zks drop.. lmao

### ISSUE THREAD

**Issue by xyphre1314** [matter-labs/zksync-era#1329]
#### 📝 Description

Provide a clear and concise description of the bug.

#### 🔄 Reproduction Steps

Steps to reproduce the behaviour

#### 🤔 Expected Behavior

Describe what you expected to happen.

#### 😯 Current Behavior

Describe what actually happened.

#### 🖥️ Environment

Any relevant environment details.

#### 📋 Additional Context

Add any other context about the problem here. If applicable, add screenshots to help explain.

#### 📎 Log Output

```
Paste any relevant log output here.
```

**Comment by Manhha1993** [comment]
airdroping

**Comment by nirobAI** [comment]
lol

**Comment by Manhha1993** [comment]
> lol

Soon

**Comment by HYeonJoc** [comment]
a beggar lololol

**Comment by sunarus** [comment]
Make gitcoin score & 0.5 - 1 eth mainnet gas spend for wallet eligible filter

**Comment by no1yukun** [comment]
lfg

**Comment by xyphre1314** [comment]
> @xyphre1314 Hahaha i think you re one of them

i love u

**Comment by bovicc** [comment]
you mint be one too

**Comment by sunarus** [comment]
Beggar mooners
