### ISSUE TITLE
CurveBabyJubJub.pointAdd calculation issue in ZKSync Era environment

### ISSUE THREAD

**Issue by duongnd-183902** [matter-labs/zksync-era#1458]
#### 📝 Description
The function addPKCommittee in my smart contract encounters an error when attempting to add a point on the BabyJub curve on ZKSync Era Sepolia and inmemory local environments. The function works as expected on Layer 1, Layer 2 Arbitrum Sepolia testnet environments.
#### 🔄 Reproduction Steps
1. Deploy contract DKG to ZKSync Era inmemory testnet environment.
2. Call the addPKCommittee function with a valid BabyJubPoint[] argument.
3. Observe the transaction failing with a revert error.
#### 🤔 Expected Behavior
The addPKCommittee function should successfully add the point to the PK_COMMITTEE variable on the BabyJub curve and the transaction should complete without reverting.
#### 😯 Current Behavior
The transaction reverts with an error message indicating "require(false) occurred".  There seems to be an error with the precompile contract 0x05 or mstore or mload in the expmod function of the CurveBabyJubJub library.
#### 🖥️ Environment
Operating System: ubuntu 22.04.3
Solidity Version: 0.8.17
Smart Contract Name: DKG
#### 📋 Additional Context
The provided BabyJub library source code seems to be functional on Layer 1 and Arbitrum Sepolia.
Link to source contract: https://github.com/duongnd-183902/DKG-zkSync.git

#### 📎 Log Output
```
Error: execution reverted (no data present; likely require(false) occurred (action="estimateGas", data="0x...", reason="require(false)", transaction={...}, invocation=null, revert=null, code=CALL_EXCEPTION, version=6.11.1)
```
#### Update
I realize that the error seems to come from the fact that zksync does not have a precompile contract 0x05, and moreover, the zksync precompile contract set is missing ecPairing. I would like to ask if there is an alternative source code for the precompile contract (ecpairing and expmod)? If not, is it possible to add more precompile contracts to zksync in the next 1-2 months?

**Comment by duongnd-183902** [comment]
There seems to be an error with the precompile contract 0x05 in the expmod function of the CurveBabyJubJub library. But i do not know how to fix that

**Comment by githubdoramon** [comment]
@duongnd-183902 unfortunately we don't yet support modexp and ecPairing indeed. We have plans to add support to them but don't have clear ETAs at the moment. There is a chance ecPairing comes within the next 2 months, but can't promise for sure yet. Please keep an eye for our announcements.

Closing this one for now.
