### ISSUE TITLE
zksync requires memecoin

### ISSUE THREAD

**Issue by dabao8888** [matter-labs/zksync-era#1477]
Memecoins are known to be a catalyst for the crypto market, playing a key role in the expansion of various networks and attracting new users to join them, the early $DOGECOIN $shiba and more recently $dogwifhat on the solana network and a series of memecoins have injected a great deal of energy into the system, zksync also has a number of memecoins, but has achieved relatively little success given the same market conditions.
zksync also has a number of memecoins, but the results have been relatively weak, in the same market conditions, I do not know the underlying reasons for this, welcome to discuss!

**Comment by ArmandwEth** [comment]
I’ve got a great idea for one if you want to help me build it
