### ISSUE TITLE
[Deployment] `zk stack init` currently broken

### ISSUE THREAD

**Issue by therealdannzor** [matter-labs/zksync-era#1820]
### 🐛 Bug Report

It errors when running the hyperchain wizard with `zk stack init` to deploy a remote network.

#### 📝 Description

Setup reverts early due to missing config that the setup should create after completion.

#### 🔄 Reproduction Steps

1. `zk stack init`
2. enter the name `$HYPER_NAME.`
3. choose L1 network `sepolia`
4. enter the RPC URL
5. enter `$DATABASE_1` url
6. enter `$DATABASE_2` url
7. enter private keys for system addresses
8. enter the etherscan API key

Observe the error message:
```
File configs/${HYPER_NAME}.toml not found
```

#### 🤔 Expected Behavior

Successful zk stack deployment.

#### 😯 Current Behavior

It errors and reverts with a missing config file.

#### 📋 Additional Context

I understand the `zk` tool is being updated and refined to increase the dev experience. That said, if there's a known workaround for deploying a network based on your latest codebase (EIP-4844 support), it would be much appreciated.

**Comment by therealdannzor** [comment]
Maybe I should have opened this in https://github.com/zkSync-Community-Hub/zksync-developers/discussions @bxpana, let me know and I can move it

**Comment by joshuacheong** [comment]
I've also noticed this problem for the demo setup as well.
```
$ zk stack demo
File configs/demo.toml not found
```

**Comment by joshuacheong** [comment]
<img width="820" alt="Screenshot 2024-05-07 at 12 49 14 PM" src="https://github.com/matter-labs/zksync-era/assets/13146403/5329e529-abe9-4d2a-bb68-44229e8245b6">
@zk-Lumi do you have any idea when the new CLI is coming?

**Comment by tgmp117** [comment]
![Screenshot 2024-05-08 152625](https://github.com/matter-labs/zksync-era/assets/42028439/6ff4abff-e196-418f-8f61-bcc6d7d2a461)
Ummm????

**Comment by Ebrahim1997r** [comment]
!!!!!!!!!

**Comment by zk-Lumi** [comment]
Thanks for reaching out @joshuacheong. A new and improved ZK Stack CLI is coming very soon (internally tested currently, should be live end of month / start of June), which will fix this issue. The current version is [deprecated](https://docs.zksync.io/zk-stack/running-a-hyperchain/locally.html) and may not function as expected.

Apologies for the inconvenience, the new CLI will be a production-ready stable release.

**Comment by zk-Lumi** [comment]
> Maybe I should have opened this in https://github.com/zkSync-Community-Hub/zksync-developers/discussions @bxpana, let me know and I can move it

This is indeed correct place to open ZK Stack related issues

**Comment by joshuacheong** [comment]
Quick check @zk-Lumi and @Deniallugo is this the PR addressing this?
https://github.com/matter-labs/zksync-era/pull/1941/

**Comment by nborah924** [comment]
Zksync

**Comment by joshuacheong** [comment]
> Quick check @zk-Lumi and @Deniallugo is this the PR addressing this?
> 
> feat(zkstack): init with new zk stack tooling #1941: #1941

Gentle reminder - is this the PR to address this?

**Comment by zk-Lumi** [comment]
Hi @joshuacheong,

This will be fixed with the new ZK CLI.

The new and improved ZK Stack CLI is comin soon (internally tested currently, should be live start of June)

Apologies for the inconvenience, the new CLI will be a production-ready stable release.

**Comment by joshuacheong** [comment]
> Hi @joshuacheong,
> 
> This will be fixed with the new ZK CLI.
> 
> The new and improved ZK Stack CLI is comin soon (internally tested currently, should be live start of June)
> 
> Apologies for the inconvenience, the new CLI will be a production-ready stable release.

Thanks a million!

**Comment by Hirama** [comment]
@joshuacheong hi wen? :D

**Comment by SergeevDmitry** [comment]
Hello. Any updates on this? It's almost the end of June
