### ISSUE TITLE
cargo.toml files point to private repositories and v1.3.1 branches

### ISSUE THREAD

**Issue by Nathan-Franck** [matter-labs/zksync-era#2]
I understand with the re-branding that there's a lot of churn with your files, here's one you missed ---

I'm trying to run through the install steps and am getting stuck doing a `cargo build` - all the dependent cargo packages in your organization are pointing to non-'era-' repositories and to a 'v1.3.1' instead of 'main' branch. I was able to text-replace all the cargo.toml files in this repository, but now some dependent packages are themselves trying to find their own non-'era-' repositories so it's best to let you know!

**Comment by bradyjoestar** [comment]
yeah, same to me

**Comment by arose0** [comment]
Thanks for flagging - all of the dependencies are open source, but of course the paths need updating. If you want to get unblocked urgently, you can change these yourself but of course this isn't ideal and with the name changes they may not all be obvious.

We'll have a fix for this up very soon! cc @shahar4 FYI.

**Comment by greyblake** [comment]
Same here.
`cargo check` fails to clone `https://github.com/matter-labs/zk_evm.git`:
```
error: failed to get `zk_evm` as a dependency of package `zksync_utils v1.0.0 
```

**Comment by shahar4** [comment]
Please try to run the project now. All the private deps were updated and the project is runnable using all public repos. Thanks for raising this! @Nathan-Franck @bradyjoestar @greyblake
