### ISSUE TITLE
Update the Twitter Logo 

### ISSUE THREAD

**Issue by niranjan-kurhade** [matter-labs/zksync-era#237]
#### 📝 Description

Update the Twitter Logo to the New logo (latest logo - X) in the docs of the Project. https://era.zksync.io/docs/

#### 🤔 Rationale

The Project should be updated with the latest changes.

#### 📋 Additional Context

![image](https://github.com/matter-labs/zksync-era/assets/97905637/5e361e89-7575-4c50-8c24-821c120d83e3)

**Comment by niranjan-kurhade** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by githubdoramon** [comment]
@niranjan-kurhade our docs repo is open and you are more than welcome to submit a PR to update the logo - https://github.com/matter-labs/zksync-web-era-docs

**Comment by niranjan-kurhade** [comment]
> @niranjan-kurhade our docs repo is open and you are more than welcome to submit a PR to update the logo - https://github.com/matter-labs/zksync-web-era-docs

Sure! Is there a need to open an Issue before? Or I can directly make a PR?
