### ISSUE TITLE
Renaming File

### ISSUE THREAD

**Issue by DikaCream** [matter-labs/zksync-era#252]
### 🌟 Feature Request
Requesting file name changing

#### 📝 Description
To avoid confusion reports , rename the GovernanceFacet to ZkFacet or DevFacet 

#### 🤔 Rationale
to avoid misunderstanding about Governance code/file

#### 📋 Additional Context

example: DEV_FACET_ADDR="0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9" 

ZK_FACET_ADDR="0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"

**Comment by DevanshKyada27** [comment]
Hey @DikaCream can I work on it.

**Comment by DevanshKyada27** [comment]
Can you please direct me where the file is located.

**Comment by DikaCream** [comment]
> Can you please direct me where the file is located.
Hi i will close this issue , i just got confirmation from the team, there will be a new L1 contract called Governor and GovernanceFacet that they have now it will be renamed to AdminFacet

**Comment by DikaCream** [comment]
i close this issue , i just got confirmation from the team, there will be a new L1 contract called Governor and GovernanceFacet that they have now it will be renamed to AdminFacet
