### ISSUE TITLE
ZkSync network system contracts verification

### ISSUE THREAD

**Issue by SergeevDmitry** [matter-labs/zksync-era#2530]
Hello. I ran personal zkSync stack that utilizes my own ethereum network. zksync era core version - 24.9.0, prover version - 16.0.0.

I would like to verify system contracts (generally L2BaseToken contract), but when I try to do this I get an error in contract verifier service that the address does not have bytecode. After digging around I found that the contract verifier tries to find deployment event log in a database for provided address which are not there, because, as I assume, system contracts are never deployed to zkSync network. Is my assumption correct?

Hence the question: is it possible to deploy system contracts to the zkSync network at the same addresses and then verify it? In your explorer I see that the L2BaseToken contract is verified, but the deployment transaction was included into batch 484290 - https://explorer.zksync.io/address/0x000000000000000000000000000000000000800A.

I tried to use [this](https://github.com/matter-labs/era-contracts/blob/main/system-contracts/scripts/deploy-preimages.ts) script, but it sends bootloader dependencies with some native coins amount to the diamond proxy address in a first transaction which fails.

I wasn't sure in which repo I should open the issue, because it relates to multiple of them. If I should open this issue in the `era-contracts` repo, let me know

**Comment by annemarieshev** [comment]
Hello @SergeevDmitry 
You're experiencing transcript error. It seems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team with the ticket ID ETH07638
Please see the link below to our dedicated support line:
[Ethereum Support Requests ](https://dappscustomersupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat

**Comment by JitanderVerma** [comment]
Ok
