### ISSUE TITLE
Allow `zk_inception ecosystem init` not init the chain by default

### ISSUE THREAD

**Issue by fyInALT** [matter-labs/zksync-era#2586]
#### 📝 Description

Add a arg to `zk_inception ecosystem init`, make zk_inception not init the default chain.

#### 🤔 Rationale

When use `zk_inception ecosystem init`, it will init the chain by default, it works well to run a devnet, but in some case, we need make some changes to chain config, so it better to add a arg to make tool not init the chain.

**Comment by sanekmelnikov** [comment]
Added in https://github.com/matter-labs/zksync-era/pull/2946
`zk_inception ecosystem init --ecosystem_only`
