### ISSUE TITLE
Missing solc for linux-arm64

### ISSUE THREAD

**Issue by thomas-nguy** [matter-labs/zksync-era#261]
I am trying to setup zksync on an aws instance with linux arm64

However at the `compile l2 contracts step` I am facing the following error

```
Error in plugin @matterlabs/hardhat-zksync-solc: Failed to download https://github.com/matter-labs/zksolc-bin/raw/main/linux-arm64/zksolc-linux-arm64-musl-v1.3.1 - 404 received.
```

After digging a bit more, I found that it does not have the  binary for linux-arm64 

https://github.com/matter-labs/zksolc-bin/tree/v1.3.15

Any plan to support it in the future?

**Comment by hatemosphere** [comment]
@thomas-nguy so, since we've identified that at least one person on this planet needs this, we now have it: https://github.com/matter-labs/zksolc-bin/tree/main/linux-arm64
