### ISSUE TITLE
Bug/Logic error in tx() method of DeployContractBuilder in zksync-rs 

### ISSUE THREAD

**Issue by sammyshakes** [matter-labs/zksync-era#27]
## Info
---

There seems to be a bug/logic error in the rust sdk that has been preventing the deployment of Child contracts from a Factory 
https://github.com/matter-labs/zksync-era/blob/48fe6e27110c1fe1a438c5375fb256890e8017b1/sdk/zksync-rs/src/operations/deploy_contract.rs#L76 it is trying to feed in only the bytecode of the contract instead of all factory deps.. I changed [this line](https://github.com/matter-labs/zksync-era/blob/48fe6e27110c1fe1a438c5375fb256890e8017b1/sdk/zksync-rs/src/operations/deploy_contract.rs#L76) from:
```
Some(vec![bytecode.clone()])
``` 
to:
 ```
Some(factory_deps)
``` 
and it worked for my use case.. 

## Error received

The error received when attempting to deploy a child contract from a SimpleFactory contract by calling `newStepChild()` [here](https://github.com/sammyshakes/sample-fzksync-project/blob/e9db7d7de2ac87e971f8f41cdb4c608122963f04/src/SimpleFactory.sol#L92).

```
ErrorObject { code: ServerError(3), message: "Failed to submit transaction: cannot estimate gas: The code hash is not known", data: Some(RawValue({"code":104,"message":"cannot estimate gas: The code hash is not known"})) }
```
Once i made the change stated above, `newStepChild()` executed and deployed successfully.
*If this is the right fix, I am happy to make a PR for it

**Comment by popzxc** [comment]
Hello! Development of SDK in this monorepo is discontinued, this SDK currently exists for some internal needs only and will be removed soon.
Please use a newer official SDK for Rust: https://era.zksync.io/docs/api/rust/
