### ISSUE TITLE
not getting syncing block

### ISSUE THREAD

**Issue by Parmanand0712** [matter-labs/zksync-era#2780]
We have started node using docker compose file

docker compose --file mainnet-external-node-docker-compose.yml up -d

# docker ps
CONTAINER ID   IMAGE                                   COMMAND                  CREATED          STATUS                    PORTS                                                                    NAMES
d0be35e6f50f   matterlabs/external-node:2.0-v24.16.0   "sh /usr/bin/entrypo…"   47 minutes ago   Up 47 minutes             127.0.0.1:3060-3061->3060-3061/tcp, 127.0.0.1:3081->3081/tcp, 3322/tcp   docker-compose-examples-external-node-1
3f9abee50835   grafana/grafana:9.3.6                   "/run.sh"                47 minutes ago   Up 47 minutes             127.0.0.1:3000->3000/tcp                                                 docker-compose-examples-grafana-1
123993998bee   postgres:14                             "docker-entrypoint.s…"   47 minutes ago   Up 47 minutes (healthy)   5430/tcp, 5432/tcp                                                       docker-compose-examples-postgres-1
a0249f690388   prom/prometheus:v2.35.0                 "/bin/prometheus --c…"   47 minutes ago   Up 47 minutes             9090/tcp                                                                 docker-compose-examples-prometheus-1

#curl -X POST http://localhost:3060 \
-H "Content-Type: application/json" \
-d '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}'
curl: (56) Recv failure: Connection reset by peer

**Comment by malingzhao** [comment]
die you zksync node is ok

**Comment by Parmanand0712** [comment]
Thanks

**Comment by malingzhao** [comment]
how did you resolve it
