### ISSUE TITLE
Cleanup: Multiple unused dependencies identified across packages

### ISSUE THREAD

**Issue by steph-mipt** [matter-labs/zksync-era#2783]
#### 📝 Description
Several unused dependencies have been identified across multiple packages in the repo. These dependencies are not being utilized and can potentially be removed to optimize the project structure and reduce unnecessary code.

#### 🔄 Reproduction Steps
1. Install the nightly version of Rust
2. Run the following command in the project root:
   ```
   cargo +nightly udeps --all-features --all-targets
   ```
3. Observe the list of unused dependencies in the output

#### 🤔 Expected Behavior
All dependencies listed in the `Cargo.toml` files should be actively used in the project.

#### 😯 Current Behavior
The `cargo udeps` tool has identified several unused dependencies across multiple packages. Here's a summary of the findings:

- `zksync_circuit_breaker`: Unused dev-dependency "assert_matches"
- `zksync_consistency_checker`: Unused dependency "zksync_eth_sender"
- `zksync_contract_verifier_lib`: Unused dependency "zksync_env_config"
- `zksync_core_leftovers`: Unused dependencies "zksync_dal" and "zksync_node_genesis"
- `zksync_da_client`: Unused dependencies "tracing", "zksync_config", and "zksync_types"
- `zksync_db_connection`: Unused dependency "zksync_health_check"
- `zksync_external_node`: Unused dependency "semver"
- `zksync_node_db_pruner`: Unused dev-dependency "test-casing"
- `zksync_node_fee_model`: Unused dev-dependency "zksync_node_test_utils"
- `zksync_node_framework`: Unused dependency "zksync_protobuf_config" and dev-dependency "zksync_env_config"
- `zksync_proof_data_handler`: Unused dependency "zksync_tee_verifier"
- `zksync_tee_verifier`: Unused dependencies "zksync_dal", "zksync_db_connection", and "zksync_queued_job_processor"
- `zksync_utils`: Unused dependency "itertools"

#### 🖥️ Environment
- Rust: nightly version (used for running `cargo udeps`)
- Project: `origin/main` branch

#### 📋 Additional Context
It's worth noting that `cargo udeps` may produce false positives in some cases, such as dependencies used only in doc-tests. However, manual verification of a few cases suggests that these dependencies are indeed unused and can be safely removed.

#### 📎 Log Output
```
unused dependencies:
`zksync_circuit_breaker v0.1.0 (/Users/steph/dev/txfusion/zksync-era/core/lib/circuit_breaker)`
└─── dev-dependencies
     └─── "assert_matches"
`zksync_consistency_checker v0.1.0 (/Users/steph/dev/txfusion/zksync-era/core/node/consistency_checker)`
└─── dependencies
     └─── "zksync_eth_sender"
`zksync_contract_verifier_lib v0.1.0 (/Users/steph/dev/txfusion/zksync-era/core/lib/contract_verifier)`
└─── dependencies
     └─── "zksync_env_config"
`zksync_core_leftovers v0.1.0 (/Users/steph/dev/txfusion/zksync-era/core/lib/zksync_core_leftovers)`
└─── dependencies
     ├─── "zksync_dal"
     └─── "zksync_node_genesis"
`zksync_da_client v0.1.0 (/Users/steph/dev/txfusion/zksync-era/core/lib/da_client)`
└─── dependencies
     ├─── "tracing"
     ├─── "zksync_config"
     └─── "zksync_types"
`zksync_db_connection v0.1.0 (/Users/steph/dev/txfusion/zksync-era/core/lib/db_connection)`
└─── dependencies
     └─── "zksync_health_check"
`zksync_external_node v24.23.0 (/Users/steph/dev/txfusion/zksync-era/core/bin/external_node)`
└─── dependencies
     └─── "semver"
`zksync_node_db_pruner v0.1.0 (/Users/steph/dev/txfusion/zksync-era/core/node/db_pruner)`
└─── dev-dependencies
     └─── "test-casing"
`zksync_node_fee_model v0.1.0 (/Users/steph/dev/txfusion/zksync-era/core/node/fee_model)`
└─── dev-dependencies
     └─── "zksync_node_test_utils"
`zksync_node_framework v0.1.0 (/Users/steph/dev/txfusion/zksync-era/core/node/node_framework)`
├─── dependencies
│    └─── "zksync_protobuf_config"
└─── dev-dependencies
     └─── "zksync_env_config"
`zksync_proof_data_handler v0.1.0 (/Users/steph/dev/txfusion/zksync-era/core/node/proof_data_handler)`
└─── dependencies
     └─── "zksync_tee_verifier"
`zksync_tee_verifier v0.1.0 (/Users/steph/dev/txfusion/zksync-era/core/lib/tee_verifier)`
└─── dependencies
     ├─── "zksync_dal"
     ├─── "zksync_db_connection"
     └─── "zksync_queued_job_processor"
`zksync_utils v0.1.0 (/Users/steph/dev/txfusion/zksync-era/core/lib/utils)`
└─── dependencies
     └─── "itertools"
Note: They might be false-positive.
      For example, `cargo-udeps` cannot detect usage of crates that are only used in doc-tests.
      To ignore some dependencies, write `package.metadata.cargo-udeps.ignore` in Cargo.toml.
```

**Comment by perekopskiy** [comment]
Thanks, resolved!
