### ISSUE TITLE
Suggestion for improvement

### ISSUE THREAD

**Issue by joohhnnn** [matter-labs/zksync-era#28]
I found that due to changes in the create and create2 algorithms, even in the case of the same address and nonce, the deployed contract address is different from other Chain. Currently, many projects use fixed addresses on all EVM chains, which can lead to unexpected errors. Can we introduce a function similar to CREATEXXXX that still uses the keccak256 algorithm (used on Ethereum to calculate the deployment contract address) to generate the contract, and allows users to specify a NONCE (if need)?

By the way, I couldn't find the code related to the EVM execution layer module in your codebase. Can you tell me where the transaction logic is executed specifically (vm)?

**Comment by popzxc** [comment]
Hello. Currently, zkEVM server-side execution logic exists in the [multivm crate](https://github.com/matter-labs/zksync-era/tree/main/core/lib/multivm) and its dependencies.
Increasing the compatibility of zkEVM and EVM is in plans, but right now having a different address on zkSync is a protocol feature.
