### ISSUE TITLE
Is the code for contract not open source in zksync-era?

### ISSUE THREAD

**Issue by shengling2008** [matter-labs/zksync-era#3]

**Comment by Nathan-Franck** [comment]
Clicking into the submodule for contracts goes to a non-public url

**Comment by shengling2008** [comment]
404

**Comment by shengling2008** [comment]
no public?

**Comment by shengling2008** [comment]
404

**Comment by shaharkaminsky** [comment]
Thanks for raising this! All of our code is open source, including the contracts! It's just that the paths need updating. Please see
- [contracts here](https://github.com/matter-labs/era-contracts)
- [system contracts here](https://github.com/matter-labs/era-system-contracts)

**Comment by shahar4** [comment]
Thanks for raising this! All of our code is open source, including the contracts! It's just that the paths need updating. Please see

[contracts here](https://github.com/matter-labs/era-contracts)
[system contracts here](https://github.com/matter-labs/era-system-contracts)

**Comment by shengling2008** [comment]
OK.

I have one more question, where is the path to openzeppelin-contracts?

Is it this path：https://github.com/OpenZeppelin/openzeppelin-contracts？

**Comment by shahar4** [comment]
The path for the Openzeppelin contracts was updated. Thanks, @shengling2008 !
