### ISSUE TITLE
Add CONTRIBUTING section in the README file and CODE_OF_CONDUCT file to the repository

### ISSUE THREAD

**Issue by singodiyashubham87** [matter-labs/zksync-era#308]
#### 📝 Description

I want to add  a "CONTRIBUTING" section in the README file and a CODE_OF_CONDUCT file to the repository

Kindly assign me this issue

**Comment by hatemosphere** [comment]
https://github.com/matter-labs/zksync-era/blob/main/CONTRIBUTING.md
it's already there
