### ISSUE TITLE
`zk test rust` error MacOS

### ISSUE THREAD

**Issue by smatthewenglish** [matter-labs/zksync-era#32]
I'm trying to run `zk test rust`, but i keep getting the following error:

```
Some errors have detailed explanations: E0277, E0609.
For more information about an error, try `rustc --explain E0277`.
warning: `zksync_dal` (lib) generated 26 warnings
error: could not compile `zksync_dal` due to 227 previous errors; 26 warnings emitted
warning: build failed, waiting for other jobs to finish...
Error: Child process exited with code 101
```

<img width="987" alt="Screen Shot 2023-05-08 at 6 34 44 PM" src="https://user-images.githubusercontent.com/9053984/236952251-8105864d-aa5e-46ef-9ec4-5bfe794618d7.png">

**Comment by hatemosphere** [comment]
please try with latest main branch head and re-open the issue if it does not work for you
