### ISSUE TITLE
Getting URL error, when instantiating with `Wallet::with_http_client()`

### ISSUE THREAD

**Issue by sammyshakes** [matter-labs/zksync-era#33]
## Info
Currently when attempting to instantiate a wallet with the `with_http_client()` method, it is returning an error if a port is not included in the rpc url.

example: when url is without a port number, such as: `https://testnet.era.zksync.dev`, an error is returned, 
but when url includes a port number, like `https://testnet.era.zksync.dev:443`, a wallet is successfully instantiated.

Unfortunately many rpc urls do not contain a port number (i.e infura links), these rpc urls are unable to successfully instantiate a wallet.

Here is code that illustrates the issue: (can be pulled from [this repo](https://github.com/sammyshakes/rpc-url-issue))

### Cargo.toml:
```toml
[dependencies]
zksync = {git = "https://github.com/matter-labs/zksync-era.git"}
zksync_eth_signer = {git = "https://github.com/matter-labs/zksync-era.git"}
```
### main.rs:
```rs
use zksync::{
    self,
    signer::Signer,
    wallet::Wallet,
    zksync_types::{L2ChainId, PackedEthSignature, H256},
};
use zksync_eth_signer::PrivateKeySigner;

const CHAIN: u16 = 280;

// Switch these comments to suppress error
const RPC_URL: &str = "https://testnet.era.zksync.dev";
// const RPC_URL: &str = "https://testnet.era.zksync.dev:443";

fn main() {
    let mut eth_private_key = H256::default();
    eth_private_key.randomize();

    let eth_signer = PrivateKeySigner::new(eth_private_key);
    let address_from_pk = PackedEthSignature::address_from_private_key(&eth_private_key).unwrap();
    let signer = Signer::new(eth_signer, address_from_pk, L2ChainId(CHAIN));

    // getting port error retrieving this wallet, if no port provided
    let wallet = Wallet::with_http_client(RPC_URL, signer);
    println!("{:#?} wallet", wallet);
}
```
When the above code is run:
```rs
cargo run
```

Output:
```rs
Err(
    RpcError(
        Transport(
            Url(
                "Port number is missing in the URL",
            ),
        ),
    ),
) wallet
```

### Clone Repo
Clone [rpc-url-issue](https://github.com/sammyshakes/rpc-url-issue)
```bash
# Clone repo
git clone https://github.com/sammyshakes/rpc-url-issue.git

# Navigate to folder
cd rpc-url-issue

#execute
cargo run
```

**Comment by mm-zk** [comment]
This error comes from jsonrpsee library, that Wallet uses underneath.

https://github.com/paritytech/jsonrpsee/issues/1048

**Comment by popzxc** [comment]
Hello! Development of SDK in this monorepo is discontinued, this SDK currently exists for some internal needs only and will be removed soon.
Please use a newer official SDK for Rust: https://era.zksync.io/docs/api/rust/
