### ISSUE TITLE
`zk init` error : solc subprocess error: Os { code: 2, kind: NotFound, message: "No such file or directory" }

### ISSUE THREAD

**Issue by morolt** [matter-labs/zksync-era#34]
-------------------------
> Creating docker volumes
✔ Creating docker volumes done (1ms)

----------------
> Pulling images
Pulling geth     ... done
Pulling postgres ... done
✔ Pulling images done (3023ms)

----------------------
> Checking environment
✔ Checking environment done (108ms)

--------------------
> Checking git hooks
✔ Checking git hooks done (4ms)

-----------------------
> Setting up containers
WARNING: Found orphan containers (zksync_dev-liquidity-token-watcher_1, zksync_dev-ticker_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
zksync_geth_1 is up-to-date
zksync_postgres_1 is up-to-date
✔ Setting up containers done (927ms)

-------------------------------------
> Checkout system-contracts submodule
✔ Checkout system-contracts submodule done (121ms)

-----------------------
> Compiling JS packages
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.97s.
yarn run v1.22.19
$ yarn npm-run-all --parallel build:*
$ /root/codes/zksync/node_modules/.bin/npm-run-all --parallel 'build:*'
$ yarn web3 build
$ yarn reading-tool build
$ yarn workspace reading-tool build
$ yarn workspace zksync-web3 build
$ tsc && cp -f typechain/*.d.ts build/typechain
$ tsc
Done in 16.83s.
✔ Compiling JS packages done (19518ms)

----------------------
> Compile l2 contracts
yarn run v1.22.19
$ /root/codes/zksync/node_modules/.bin/hardhat compile
Nothing to compile
Done in 1.69s.
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.93s.
yarn run v1.22.19
$ /root/codes/zksync/etc/system-contracts/node_modules/.bin/hardhat compile
Nothing to compile
Creating Typechain artifacts in directory typechain for target ethers-v5
Successfully generated Typechain artifacts!
Done in 9.50s.
yarn run v1.22.19
$ rm -rf ./bootloader/build && yarn ts-node scripts/process.ts
$ /root/codes/zksync/etc/system-contracts/node_modules/.bin/ts-node scripts/process.ts
Preprocessing production bootloader
Preprocessing playground block bootloader
Preprocessing gas test bootloader
Preprocessing fee estimation bootloader
Preprocessing done!
Done in 6.34s.
yarn run v1.22.19
$ /root/codes/zksync/etc/system-contracts/node_modules/.bin/hardhat run ./scripts/compile-yul.ts
Creating Typechain artifacts in directory typechain for target ethers-v5
Successfully generated Typechain artifacts!
solc subprocess error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
Error: Child process exited with code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Child process exited with code 1
root@ubuntu:~/codes/zksync# cat /etc/issue
Ubuntu 22.04.2 LTS \n \l

**Comment by Niet-Pham** [comment]
you need install solc

**Comment by shahar4** [comment]
Indeed. Please refer to `(docs/setup-dev.md` to see all you need to set up your env.
