### ISSUE TITLE
Feature: Adding contributors section to the README.md file

### ISSUE THREAD

**Issue by Kalyanimhala** [matter-labs/zksync-era#347]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/matter-labs/zksync-era/assets/147402107/307de4ad-edb2-42d5-a234-fa115e4fbf52)

**Comment by Kalyanimhala** [comment]
@popzxc Kindly assign me this issue, I want to work on it. Thank You!!

**Comment by popzxc** [comment]
Hello! Thanks for the suggestion, we do value any contributions a lot.
However, we don't think that we should add the list of contributors to the readme, given that it's already present on the repository page natively. Adding it would just duplicate the information and make the readme file harder to process.

<img width="310" alt="image" src="https://github.com/matter-labs/zksync-era/assets/12111581/d41dd4ea-8b7b-4f61-8a64-7666adbab231">
