### ISSUE TITLE
Transaction Receipt contains invalid data.

### ISSUE THREAD

**Issue by davidqhr** [matter-labs/zksync-era#44]
Sometimes the eth_getTransactionReceipt returns a receipt with an empty blockNumber and empty logs. If resend the request after a few seconds, It's likely to get a standard receipt with fields filled correctly. Is this a bug or I missed something?

**Comment by popzxc** [comment]
Does the issue still reproduce?

**Comment by patapata24** [comment]
i think it is a bug
