### ISSUE TITLE
when I run   "zk  init" ，there's an error，

### ISSUE THREAD

**Issue by ccx997t** [matter-labs/zksync-era#47]
I use the main branch to deploy the project，when I   run   "zk  init",   how to fix it

> Running server genesis setup
    Updating git repository `https://github.com/matter-labs/era-zk_evm.git`
    Updating git repository `https://github.com/matter-labs/era-zkEVM-assembly.git`
    Updating git repository `https://github.com/matter-labs/era-zkevm_test_harness.git`
    Updating git repository `https://github.com/matter-labs/era-circuit_testing.git`
    Updating git repository `https://github.com/matter-labs/era-zkevm_opcode_defs.git`
    Updating crates.io index
    Updating git repository `https://github.com/matter-labs/era-sync_vm.git`
error: failed to select a version for `regex`.
    ... required by package `zkevm-assembly v1.3.2 (https://github.com/matter-labs/era-zkEVM-assembly.git?branch=v1.3.2#8a339104)`
    ... which satisfies git dependency `zkevm-assembly` of package `vm v0.1.0 (/mnt/volume_nyc1_02/zksync-era/core/lib/vm)`
    ... which satisfies path dependency `vm` (locked to 0.1.0) of package `system-constants-generator v0.1.0 (/mnt/volume_nyc1_02/zksync-era/core/bin/system-constants-generator)`
versions that meet the requirements `^1.8` are: 1.8.4, 1.8.3, 1.8.2, 1.8.1, 1.8.0

all possible versions conflict with previously selected packages.

  previously selected package `regex v1.7.3`
    ... which satisfies dependency `regex = "^1.5"` (locked to 1.7.3) of package `actix-router v0.5.1`
    ... which satisfies dependency `actix-router = "^0.5"` (locked to 0.5.1) of package `actix-web v4.3.1`
    ... which satisfies dependency `actix-web = "^4"` (locked to 4.3.1) of package `actix-cors v0.6.4`
    ... which satisfies dependency `actix-cors = "^0.6.0-beta.2"` (locked to 0.6.4) of package `zksync_core v1.0.0 (/mnt/volume_nyc1_02/zksync-era/core/bin/zksync_core)`
    ... which satisfies path dependency `zksync_core` (locked to 1.0.0) of package `zksync_external_node v1.0.0 (/mnt/volume_nyc1_02/zksync-era/core/bin/external_node)`

failed to select a version for `regex` which could resolve this conflict

**Comment by Niet-Pham** [comment]
![image](https://github.com/matter-labs/zksync-era/assets/55547523/2018554b-0843-4e65-95ac-7b41aeba57bc)
I ran `cargo update --package regex` but when run `zk init` again. I got new error? Did you see it?

**Comment by ccx997t** [comment]
> 
I  also got this error when I run zk init

     Running `target/release/zksync_server --genesis`
2023-06-16T07:11:45.657797Z  INFO zksync_core::genesis: running regenesis
thread 'main' panicked at 'Can't read .zbin bytecode at "/mnt/volume_nyc1_02/zksync-era/etc/system-contracts/contracts/precompiles/artifacts/Keccak256.yul/Keccak256.yul.zbin": No such file or directory (os error 2)', core/lib/contracts/src/lib.rs:195:31
stack backtrace:
   0:     0x56398d6f7cfa - std::backtrace_rs::backtrace::libunwind::trace::h79937bc171ada62c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x56398d6f7cfa - std::backtrace_rs::backtrace::trace_unsynchronized::h2292bca8571cb919
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56398d6f7cfa - std::sys_common::backtrace::_print_fmt::h9c461f248e4ae90d
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x56398d6f7cfa - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he9fe6bf1a39182e1
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x56398d71e30e - core::fmt::write::h032658c119c720d7

**Comment by emilianobonassi** [comment]
@ccx997t @Niet-Pham 

submodules are not pointing to the latest version, I've faced too

you have to go to the contracts and etc/system-contracts folder and checkout with git for the latest version

here's the patch https://github.com/emilianobonassi/zksync-era/commit/38e0b49852ebf1dbd1697135ddd14db580514c66

you could face a few small issues then, if you want to run easily I did a fork with the patches needed

https://github.com/emilianobonassi/zksync-era

**Comment by hatemosphere** [comment]
should work now from latest head of main repo. please reopen if it does not.
