### ISSUE TITLE
Determine smart contract with Layer 1

### ISSUE THREAD

**Issue by terryyyz** [matter-labs/zksync-era#58]
Hi there,

I have a smart contract on Ethereum that was created using the CREAT2 opcode, and now I intend to deploy it on Zksync Era while maintaining the same address as on Ethereum. However, I've discovered that Zksync Era utilizes a different method for calculating smart contract addresses. Is there any way for me to solve this issue ?.

Thanks for reading.

**Comment by popzxc** [comment]
No, keeping the same address for the contract on L1 and L2 is not supported.
