### ISSUE TITLE
Unable to set gasLimit

### ISSUE THREAD

**Issue by Akira-Taniguchi** [matter-labs/zksync-era#6]
# What I want to do
I want to set gasLimit when executing zksync.Wallet's transfer function.

# What I need help with
When I set gasLimit, I get an error "invalid object key - maxFeePerGas
When I set maxFeePerGas, I get an error "pre-eip-1559 transaction do not support".

**Comment by popzxc** [comment]
Hello! Please follow [the documentation for our JS SDK](https://era.zksync.io/docs/api/js/), it comes with code examples that should help you get the code running.
