### ISSUE TITLE
Deprecated zksolc compiler version in hardhat config file

### ISSUE THREAD

**Issue by olehnikolaiev** [matter-labs/zksync-era#61]
I get an error during `zk init` command execution at the commit `1283a410c918568808de7897f3b4bb6b57da98a0`:

```
> Compile l2 contracts
yarn run v1.22.19
$ /home/zk-module-experimental/node_modules/.bin/hardhat compile
Nothing to compile
Done in 0.52s.
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.28s.
yarn run v1.22.19
$ /home/zk-module-experimental/etc/system-contracts/node_modules/.bin/hardhat compile
Error in plugin @matterlabs/hardhat-zksync-solc: Deprecated zksolc compiler version in hardhat config file (1.3.1). Please use versions 1.3.13 to 1.3.13.
```
when I tried to change the version from `1.3.1` to `1.3.13` I got an error
```
$ /home/zk-module-experimental/etc/system-contracts/node_modules/.bin/hardhat run ./scripts/compile-yul.ts
Creating Typechain artifacts in directory typechain for target ethers-v5
Successfully generated Typechain artifacts!
Error: (0 , hardhat_zksync_solc_1.getZksolcPath) is not a function
```

my command history
```
 2083  zk
 2084  zk init
 2085  cargo update --package regex
 2086  zk init
 2087  cd etc/system-contracts/
 2088  yarn add -D @matterlabs/hardhat-zksync-solc
 2089  cd ../../
 2090  zk clean --all && zk init
```
could you please help me with that?

**Comment by DSHIVAAY-23** [comment]
sudo snap install solc
this might help you

**Comment by she110ff** [comment]
`
----------------------
> Compile l2 contracts
yarn run v1.22.19                                                                                                                                                                  
$ /usr/src/zksync/node_modules/.bin/hardhat compile                                                                                                                                
Nothing to compile
Done in 2.77s.                                                                                                                                                                     
yarn install v1.22.19                                                                                                                                                              
[1/4] Resolving packages...                                                                                                                                                        
[2/4] Fetching packages...                                                                                                                                                         
[3/4] Linking dependencies...                                                                                                                                                      
warning " > @matterlabs/hardhat-zksync-deploy@0.5.2" has incorrect peer dependency "zksync-web3@^0.11.1".                                                                          
warning " > @matterlabs/hardhat-zksync-solc@0.4.1" has incorrect peer dependency "hardhat@^2.14.0".                                                                                
warning " > @typechain/ethers-v5@10.1.0" has unmet peer dependency "@ethersproject/abi@^5.0.0".                                                                                    
warning " > @typechain/ethers-v5@10.1.0" has unmet peer dependency "@ethersproject/bytes@^5.0.0".                                                                                  
warning " > @typechain/ethers-v5@10.1.0" has unmet peer dependency "@ethersproject/providers@^5.0.0".                                                                              
warning " > hardhat-typechain@0.3.5" has incorrect peer dependency "typechain@^4.0.1".                                                                                             
[4/4] Building fresh packages...                                                                                                                                                   
Done in 68.53s.                                                                                                                                                                    
yarn run v1.22.19                                                                                                                                                                  
$ /usr/src/zksync/etc/system-contracts/node_modules/.bin/hardhat compile                                                                                                           
Error in plugin @matterlabs/hardhat-zksync-solc: Deprecated zksolc compiler version in hardhat config file (1.3.7). Please use versions 1.3.13 to 1.3.13.

ZkSyncSolcPluginError: Deprecated zksolc compiler version in hardhat config file (1.3.7). Please use versions 1.3.13 to 1.3.13.
    at Function.getDownloaderWithVersionValidated (/usr/src/zksync/etc/system-contracts/node_modules/@matterlabs/hardhat-zksync-solc/src/compile/downloader.ts:55:23)
    at async /usr/src/zksync/etc/system-contracts/node_modules/@matterlabs/hardhat-zksync-solc/src/index.ts:77:34
    at async OverriddenTaskDefinition._action (/usr/src/zksync/etc/system-contracts/node_modules/@matterlabs/hardhat-zksync-solc/src/index.ts:76:5)
    at async Environment._runTaskDefinition (/usr/src/zksync/etc/system-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at async Environment.run (/usr/src/zksync/etc/system-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
    at async SimpleTaskDefinition.action (/usr/src/zksync/etc/system-contracts/node_modules/hardhat/src/builtin-tasks/compile.ts:1308:9)
    at async Environment._runTaskDefinition (/usr/src/zksync/etc/system-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at async Environment.run (/usr/src/zksync/etc/system-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
    at async SimpleTaskDefinition.action (/usr/src/zksync/etc/system-contracts/node_modules/hardhat/src/builtin-tasks/compile.ts:1411:7)
    at async Environment._runTaskDefinition (/usr/src/zksync/etc/system-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
error Command failed with exit code 1.                                                                                                                                             
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.                                                                                               
Error: Child process exited with code 1

`
I have the same issue.

**Comment by olehnikolaiev** [comment]
> sudo snap install solc this might help you

after that I got
```
> Building contracts
yarn run v1.22.19
$ yarn workspace l1-zksync-contracts build
$ hardhat compile
Nothing to compile
Creating Typechain artifacts in directory typechain for target ethers-v5
Successfully generated Typechain artifacts!
Done in 6.28s.
yarn run v1.22.19
$ yarn workspace l2-zksync-contracts build
$ hardhat compile
Solidity 0.8.19 is not fully supported yet. You can still use Hardhat, but some features, like stack traces, might not work correctly.

Learn more at https://hardhat.org/hardhat-runner/docs/reference/solidity-support

Error HH409: Trying to import ./interfaces/IL2Weth.sol from cache-zk/solpp-generated-contracts/bridge/L2WETH.sol, but it has an incorrect casing.

For more info go to https://hardhat.org/HH409 or run Hardhat with --show-stack-traces
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /home/.nvm/versions/node/v16.19.1/bin/node
Arguments: /home/.yarn/lib/cli.js build
Directory: /home/zk-module-experimental/contracts/zksync
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Child process exited with code 1
```
solc version is `Version: 0.5.16+commit.9c3226ce.Linux.g++`

**Comment by she110ff** [comment]
https://github.com/matter-labs/zksync-era/issues/51#issuecomment-1610893857

**Comment by olehnikolaiev** [comment]
> 

thanks, it worked!

**Comment by kladkogex** [comment]
Nice!

**Comment by hatemosphere** [comment]
should be working with no kludges in current head of main branch. please feel free to create another issue of it does not

**Comment by Pulo25** [comment]
> sudo snap install solc this might help you

Thanks a lot
