### ISSUE TITLE
Requesting for traces is not available for historical blocks

### ISSUE THREAD

**Issue by penspencap** [matter-labs/zksync-era#63]
Hello, I can't get the traces before block 2219807. 

This is the example for the request
```shell
curl --location 'https://mainnet.era.zksync.io' \
--header 'Content-Type: application/json' \
--data ' {
  "jsonrpc": "2.0",
  "method": "debug_traceBlockByNumber",
  "params": [
    "0x4995d", 
    {
      "tracer": "callTracer",
      "tracerConfig": {"onlyTopCall": false}
    }
  ],
  "id": 1
}
'
```

```shell
-- response
{
    "jsonrpc": "2.0",
    "result": [],
    "id": 1
}
```
And I can find the tx in this block in scan https://explorer.zksync.io/block/301405 . It should not be empty.

**Comment by popzxc** [comment]
Currently, the traces are saved during the execution of transactions, and not generated dynamically. Thus, traces aren't available for the blocks that were created before this feature was introduced. This may be changed to a dynamic implementation in the future, but right now there is no way to obtain historical traces, unfortunately.
