### ISSUE TITLE
zk prover thing is not working on terminals

### ISSUE THREAD

**Issue by DSHIVAAY-23** [matter-labs/zksync-era#65]

**Comment by prakashksinha** [comment]
@zksync-team - any update on this. it's been couple of months already

**Comment by hatemosphere** [comment]
@prakashksinha @DSHIVAAY-23 it is really hard to guess what's not working with zero details provided. please reopen the issue with step of step guide on how to reproduce what's not working on your side and we'll gladly help to resolve it.
