### ISSUE TITLE
zksync_object_store has broken dependencies

### ISSUE THREAD

**Issue by Gilgamesh-818** [matter-labs/zksync-era#66]
The google-cloud-default dependency no longer exists inside the git repo 

https://github.com/yoshidan/google-cloud-rust?branch=main

Also I believe the ClientConfig struct has been changed such that some methods defined in gcs.rs, a file in object_store's src, are no longer found. Maybe I have a fundamental misunderstanding of the issue but it seems like the yoshida google-cloud-rust fork has undergone a breaking update and the dependencies in zksync_object_store no longer function as intended.

(zksync_object_store, path=zksync-era/core/lib/object_store)

**Comment by hatemosphere** [comment]
should be working with current head of main branch
