### ISSUE TITLE
Genesis block mismatch with main node

### ISSUE THREAD

**Issue by YanhaoJiang** [matter-labs/zksync-era#69]
I pulled externel node image in docker hub and run with main-net configs, version is matterlabs/external-node-public:v0.0.6.

Then it failed and there's log.

Could someone help me?

"2023-07-21T02:14:39.239989Z  INFO zksync_core::genesis: operations_schema_genesis is complete
CONTRACTS_GENESIS_ROOT=0x668e46ea2b4c67fbaf7c6fa3fa2e6c29d1215847a503c29372d7301a2b50c997
CONTRACTS_GENESIS_BLOCK_COMMITMENT=0x4d7766c608dc5a3fdbba2c52fb7e09754904f966a3eaf8af85ca1a77be7176d5
CONTRACTS_GENESIS_ROLLUP_LEAF_INDEX=22
CHAIN_STATE_KEEPER_BOOTLOADER_HASH=0x010007794e73f682ad6d27e86b6f71bbee875fc26f5708d1713e7cfd476098d3
CHAIN_STATE_KEEPER_DEFAULT_AA_HASH=0x0100067d861e2f5717a12c3e869cfb657793b86bbb0caa05cc1421f16c5217bc
thread 'main' panicked at 'Genesis block root hash mismatch with main node: expected 0x668e…c997, got 0xbc59…ba95', /usr/src/zksync/core/bin/zksync_core/src/sync_layer/genesis.rs:46:9
stack backtrace:
   0:       0x4001b46f7a - std::backtrace_rs::backtrace::libunwind::trace::h79937bc171ada62c"

**Comment by YanhaoJiang** [comment]
Here is my command and postgres is working well.

docker run --network=jiangnetwork -p 3060:3060 --env-file /Lib/zksync-era/docs/external-node/prepared_configs/mainnet-config.env --mount type=bind,source=/Lib/zksync-era/docker/external-node/local_db,target=/home/local_db matterlabs/external-node-public:v0.0.6

**Comment by liusDong** [comment]
same error are u solved it？

**Comment by YanhaoJiang** [comment]
No, still error

**Comment by popzxc** [comment]
Hello! Right now the external is in alpha phase and syncing from genesis is not supported. This feature is in plans though, and hopefully the external node will be released for everyone relatively soon.
