### ISSUE TITLE
Drop postgres db 

### ISSUE THREAD

**Issue by DSHIVAAY-23** [matter-labs/zksync-era#72]
Dropping DB...
error: error communicating with database: failed to lookup address information: Temporary failure in name resolution
Error: Child process exited with code 1

**Comment by hatemosphere** [comment]
please recreate the issue if you still experience it and provide full step by step guide to reprosuce it

**Comment by ChengYueJia** [comment]
Met same error. Bugfix by modify https://github.com/matter-labs/zksync-era/blob/c1f2f5e33de90244f12fa22e10f8a40a4a2d9cdb/etc/env/docker.toml#L1 with `database_url = "postgres://postgres:notsecurepassword@localhost/zksync_local"
`
