### ISSUE TITLE
zk init error

### ISSUE THREAD

**Issue by jeff0723** [matter-labs/zksync-era#73]
Hi,
I tried to run the repo by following the instructions.

However,
I have this error when I am running `zk init`

```Error HH409: Trying to import ./interfaces/IL2Weth.sol from cache-zk/solpp-generated-contracts/bridge/L2WETH.sol, but it has an incorrect casing.```

**Comment by DSHIVAAY-23** [comment]
i have the same issue 
it will be helpfull if you get any solution of it

**Comment by hyunchel** [comment]
Can you reproduce this issue? It seems like `incorrect casing` issue has been resolved with this commit: https://github.com/matter-labs/era-contracts/commit/0697bcc395476402ffdcdc698c5c963ad7ddceba

**Comment by hatemosphere** [comment]
should we working on latest head of main
