### ISSUE TITLE
Docs on running external-node and a working example

### ISSUE THREAD

**Issue by alexqrid** [matter-labs/zksync-era#738]
#### 📝 Description

Current documentation is not sufficient to run the external-node, also the image can't be build from the [Dockerfile](https://github.com/matter-labs/zksync-era/blob/main/docker/external-node/Dockerfile) as it fails on [the copy stage of the contracts](https://github.com/matter-labs/zksync-era/blob/0804674f2c4e8ba26280f67a85705b3d8d4fdae7/docker/external-node/Dockerfile#L31)
#### 🤔 Rationale

Community should be able to run its own RPC node

**Comment by yorickdowne** [comment]
Try https://github.com/CryptoManufaktur-io/era-docker

It is currently permissioned however. The snapshot is not available publicly afaik

**Comment by Deniallugo** [comment]
Currently it isn't possible to run the external node permissionlessly, but we're working on that. Stay tuned!

**Comment by wangjiangw** [comment]
> Currently it isn't possible to run the external node permissionlessly, but we're working on that. Stay tuned!

@Deniallugo , is there any way to participate in running the external node ? we really hope to run the node, we are top rpc providers in asia, and really want to work with zksync team.
