### ISSUE TITLE
zksync_data_restore

### ISSUE THREAD

**Issue by franciscotobar** [matter-labs/zksync-era#77]
Im trying to test the `data-restore` tool, that is inside the https://github.com/matter-labs/zksync-era/blob/main/infrastructure/zk/src/run/data-restore.ts.

But there is no implementation inside `core` or `docker` folder and I cannot find anything in the changelog.

Is this feature deprecated?

In `zksync-lite` this feature can be used to recover the funds but not to have the system working again after doing the recovery, since the proof data is not recovered, in `zksync-era` its going to behave in the same way or maybe I'm missing something.

Thank you in advance for your help.

**Comment by hatemosphere** [comment]
the same tool for Era to restore state of the chain is still in development, please follow the announcements
