### ISSUE TITLE
[BUG]: Wrong Warning Phrase on Zksync Bridge Website

### ISSUE THREAD

**Issue by 0xKafi** [matter-labs/zksync-era#78]
How to find the Issue : 
1.  Visit : https://portal.zksync.io/bridge/withdraw
2.  Connect Trust Wallet using WalletConnect Features
3.  Scroll down

![image](https://github.com/matter-labs/zksync-era/assets/91113498/1b104a63-1cfd-49d5-852f-3ff6081b01df)

Warning phrase is : 
" Change network manually to zkSync Era Mainnet in your Trust Wallet is a secure and easy-to-use mobile wallet wallet "

Warning phrase must be something like this or related: 
" Change network manually to zkSync Era Mainnet in your Trust Wallet. Trust Wallet is a secure and easy-to-use mobile wallet  "

**Comment by hatemosphere** [comment]
not related to this repo.

ps. please try new bridge https://zksync.io/explore#bridges and feel free to report the issue in our Discord if it's still there.
