### ISSUE TITLE
Running `zk server` terminal auto killed the process

### ISSUE THREAD

**Issue by Niet-Pham** [matter-labs/zksync-era#8]
I'm trying to run `zk server` but it runs about 15s - 1m terminal show:
![image](https://user-images.githubusercontent.com/55547523/223315942-dd4d4b85-cc69-4349-9979-d4f57f0f5441.png)
I don't see any error log
Can anyone explain to me?

**Comment by shahar4** [comment]
Thanks for raising this @Niet-Pham. The project has been updated so please try to run it now.

**Comment by Niet-Pham** [comment]
Now I need to know hardware requirements for running zksync? Can you have any recommend?
I tried with CPU 8 core, 20GB ram, 120 GB HDD but this used too much memory

**Comment by myx75** [comment]
@Niet-Pham maybe OOM
