### ISSUE TITLE
debug_traceCall can't support  custom tracer or withLog in tracerConfig

### ISSUE THREAD

**Issue by jiangbo0216** [matter-labs/zksync-era#88]
in geth:

1. support a custom tracer can be implemented in either Go or Javascript.
2. withLog: true instructs the tracer to also collect the logs emitted during each call.

Do we have any plans or strategies in place for this requirement?

**Comment by jiangbo0216** [comment]
@shahar4
 I'm sorry for bothering you. May I ask if there is any planned support for this?

**Comment by popzxc** [comment]
Hello! I agree that these features may be useful, but right now we're not planning to add them.

**Comment by popzxc** [comment]
Closing for now.
