### ISSUE TITLE
Errors with initialising Hyperchain

### ISSUE THREAD

**Issue by samtvlabs** [matter-labs/zksync-era#92]
I am trying to spin up hyperchains and have run into the following issues

- **getZkSolcPath deprecated** : This was removed from [@matterlabs/hardhat-zksync-solc](https://www.npmjs.com/package/@matterlabs/hardhat-zksync-solc) [here](https://github.com/matter-labs/hardhat-zksync/commit/9ec8ae6eec1b5e3dc05207bb50e6954a2b1bf7ba) , but is still a dependency for the compile-yul script responsible for buidling the system contracts. As a result the compilation fails. 
- **zksolc binary cannot write to `-o`**: I have tried to bypass the issue above by downloading the latest [zk-solc-bin](https://github.com/matter-labs/zksolc-bin/blob/main/linux-amd64/zksolc-linux-amd64-musl-v1.3.14), adding it to my path and hard coding the path in the script. However , it appears that the binary cannot find the output directories 

```
 zksolc /home/ubuntu/zksync-era/etc/system-contracts/contracts/EventWriter.yul  --optimize 3 --system-mode --yul --bin --overwrite -o /home/ubuntu/zksync-era/etc/system-contracts/
No such file or directory (os error 2)
```

- **[zksolc 1.3.14](https://github.com/matter-labs/zksolc-bin/blob/main/linux-amd64/zksolc-linux-amd64-musl-v1.3.14) cannot parse yul**: When we drop the `-o` option, it seems like it is unable to parse yul. 

```shell
zksolc /home/ubuntu/zksync-era/etc/system-contracts/contracts/EventWriter.yul 
ParserError: Expected identifier but got 'StringLiteral'
 --> /home/ubuntu/zksync-era/etc/system-contracts/contracts/EventWriter.yul:7:8:
  |
7 | object "EventWriter" {
  |        ^^^^^^^^^^^^^


Error(s) found. Compilation aborted
```

**Comment by Genysys** [comment]
Update: I was using 1.3.1 . I.3.14 compiles it .
