### ISSUE TITLE
The RPC eth_call method for ownerOf is taking a long time

### ISSUE THREAD

**Issue by conan-xyz** [matter-labs/zksync-era#94]
We've established our own external-node (EN) and have observed that invoking the eth_call API for the ownerOf method in our smart contract over the internal network is significantly time-consuming, exceeding 150ms per call. In contrast, other methods like balanceOf take only around 20ms.

Is there any potential for optimization in the code that handles the ownerOf method?

here is a example：
```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","id":2,"method":"eth_call","params":[{"from":"0x0000000000000000000000000000000000000000","data":"0x6352211e00000000000000000000000000000000000000000000000000000000000004B8","to":"0xfd3fefac33edad66d3bc610c9e1fc80a34d7e9cf"},"0xCD5EFD"]}'  rpc_endpoint
```

**Comment by popzxc** [comment]
We're constantly working on optimizing the VM performance.
This tracker, however, is to track issues related for the code of the server or its components.
If you need help or suggestions, you can ask a question on [the official Discord server](https://join.zksync.dev/).
