### ISSUE TITLE
bug: Error: Genesis is not needed as L1 verifier key does not match the one in the config

### ISSUE THREAD

**Issue by ChengYueJia** [matter-labs/zksync-era#965]
#### 📝 Description

Meet error when genesis chain. error logs as below:

* try to fix but failed.
I've been tried to bugfix by follow below
 https://github.com/matter-labs/zksync-era/blob/d562a4ec15aab3b8bcde8cee81c32aea47274c16/docs/guides/launch.md#L160-L255

It dones work. Seems like not the same reason caused the bug.

#### 🔄 Reproduction Steps

```bash
zk stack init
```

or 
```bash
zk init
```

#### 🤔 Expected Behavior

successfully init.

#### 🖥️ Environment

* ubuntu
* comimt: 8f55cae360709e1ac99ffc4398174938ca61ec54

#### 📋 Additional Context

Add any other context about the problem here. If applicable, add screenshots to help explain.

#### 📎 Log Output

```
> Running server genesis setup
    Finished release [optimized] target(s) in 0.51s
     Running `target/release/zksync_server --genesis`
2024-01-30T03:36:55.074045Z  INFO zksync_server: No sentry URL was provided
2024-01-30T03:36:55.081414Z  INFO zksync_dal::connection: Created pool with 1 max connections and None statement timeout
thread 'main' panicked at /mnt/paul/zksync-era/core/lib/zksync_core/src/lib.rs:144:13:
assertion `left == right` failed: L1 verifier key does not match the one in the config
  left: 0x750d8e21be7555a6841472a5cacd24c75a7ceb34261aea61e72bb7423a7d30fc
 right: 0x8574e152c41dc39a2ecab984545e1cf21cb3ec250b919018a8053f2fa270784f
stack backtrace:
   0:     0x5649f1d4bf0c - std::backtrace_rs::backtrace::libunwind::trace::h68b3f03db065435f
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5649f1d4bf0c - std::backtrace_rs::backtrace::trace_unsynchronized::hcc29d957a519c467
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5649f1d4bf0c - std::sys_common::backtrace::_print_fmt::h51e5567c7446b80e
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5649f1d4bf0c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h54890bb4d0b3c330
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5649f1d7a75c - core::fmt::rt::Argument::fmt::heae7cd8ccc900aeb
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/core/src/fmt/rt.rs:138:9
   5:     0x5649f1d7a75c - core::fmt::write::hc761729f1163b685
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/core/src/fmt/mod.rs:1094:21
   6:     0x5649f1d4832e - std::io::Write::write_fmt::hd8de790e313b58ee
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/io/mod.rs:1714:15
   7:     0x5649f1d4bcf4 - std::sys_common::backtrace::_print::h1b2adaff5c947b3b
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5649f1d4bcf4 - std::sys_common::backtrace::print::hf6a9b81f93e62890
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5649f1d4d9aa - std::panicking::panic_hook_with_disk_dump::{{closure}}::h663629ab1a73f13e
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panicking.rs:278:22
  10:     0x5649f1d4d697 - std::panicking::panic_hook_with_disk_dump::h7dc7628c0cba33b1
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panicking.rs:312:9
  11:     0x5649f1d4dfab - std::panicking::default_hook::h4cb3ec769d1db09c
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panicking.rs:239:5
  12:     0x5649f1d4dfab - std::panicking::rust_panic_with_hook::hdd1521f6ef2543b7
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panicking.rs:729:13
  13:     0x5649f1d4dea7 - std::panicking::begin_panic_handler::{{closure}}::h7c4ede115dee30b0
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panicking.rs:621:13
  14:     0x5649f1d4c436 - std::sys_common::backtrace::__rust_end_short_backtrace::habd7cadfbd319a50
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/sys_common/backtrace.rs:170:18
  15:     0x5649f1d4dbf2 - rust_begin_unwind
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panicking.rs:617:5
  16:     0x5649ef8986e3 - core::panicking::panic_fmt::hb85e049a4301ecd3
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/core/src/panicking.rs:67:14
  17:     0x5649ef898a65 - core::panicking::assert_failed_inner::h55bb78ccfd398772
  18:     0x5649ef78183f - core::panicking::assert_failed::hdf83221136eec682
  19:     0x5649efd0ba9f - zksync_core::genesis_init::{{closure}}::hde7f608870e40c98
  20:     0x5649efd94976 - zksync_server::main::{{closure}}::hbd6099127ab0cbe5
  21:     0x5649efd85ce0 - tokio::runtime::park::CachedParkThread::block_on::hd9ee394ffa89bf32
  22:     0x5649eff8c1c7 - tokio::runtime::context::runtime::enter_runtime::hf3cb3661c796f4b1
  23:     0x5649efaf2d9b - tokio::runtime::runtime::Runtime::block_on::hef49d5108193610a
  24:     0x5649eff982d2 - zksync_server::main::hac1e3de46b4141ad
  25:     0x5649efd51493 - std::sys_common::backtrace::__rust_begin_short_backtrace::h15e18c5ea404276a
  26:     0x5649efeb6cfd - std::rt::lang_start::{{closure}}::h1ec87cb59cedcbf8
  27:     0x5649f1d3ec5b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h15d49bc2cec08bca
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/core/src/ops/function.rs:284:13
  28:     0x5649f1d3ec5b - std::panicking::try::do_call::h7e6046cce1796a4c
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panicking.rs:524:40
  29:     0x5649f1d3ec5b - std::panicking::try::h7a03f577141ecafa
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panicking.rs:488:19
  30:     0x5649f1d3ec5b - std::panic::catch_unwind::hf8b5488fd0ea6e9f
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panic.rs:142:14
  31:     0x5649f1d3ec5b - std::rt::lang_start_internal::{{closure}}::h6830acc6e473b9c7
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/rt.rs:148:48
  32:     0x5649f1d3ec5b - std::panicking::try::do_call::h4a5f68ee94ccb8f2
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panicking.rs:524:40
  33:     0x5649f1d3ec5b - std::panicking::try::hf5a7a97c92e8e8b4
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panicking.rs:488:19
  34:     0x5649f1d3ec5b - std::panic::catch_unwind::h0d98fd51ab78927d
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panic.rs:142:14
  35:     0x5649f1d3ec5b - std::rt::lang_start_internal::he20da38a2539432c
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/rt.rs:148:20
  36:     0x5649eff983b5 - main
  37:     0x7f2b3b829d90 - <unknown>
  38:     0x7f2b3b829e40 - __libc_start_main
  39:     0x5649ef8c6615 - _start
  40:                0x0 - <unknown>
Error: Genesis is not needed (either Postgres DB or tree's Rocks DB is not empty)
```

**Comment by ChengYueJia** [comment]
I've been add more detail log, which shows both the batch_size and are empty.

```
2024-01-31T14:09:47.034616Z ERROR zksync_witness_generator: batch_size is empty: true
2024-01-31T14:09:47.034636Z ERROR zksync_witness_generator: protocol_versions is empty: true
```

**Comment by ChengYueJia** [comment]
The new version seems haven been fixed. 0759fb76c4445da394c7236ac17d998deff12d93

**Comment by devudilip** [comment]
I have updated code, but still see the above error. 

`zk stack demo`

`  Running `target/release/zksync_server --genesis`
2024-02-23T20:25:11.554778Z  INFO zksync_server: No sentry URL was provided
2024-02-23T20:25:11.591532Z  INFO zksync_dal::connection: Created DB pool with parameters ConnectionPoolBuilder { max_size: 1, acquire_timeout: 30s, statement_timeout: None }
Error: genesis_init

Caused by:
    0: Call to contract failed: Api error: code 429
    1: Api error: code 429
    2: code 429

Stack backtrace:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/backtrace.rs:331:13
   3: std::backtrace::Backtrace::capture
             at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/backtrace.rs:297:9
   4: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
   5: zksync_core::genesis_init::{{closure}}
   6: zksync_server::main::{{closure}}
   7: tokio::runtime::park::CachedParkThread::block_on
   8: tokio::runtime::context::runtime::enter_runtime
   9: tokio::runtime::runtime::Runtime::block_on
  10: zksync_server::main
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: std::rt::lang_start::{{closure}}
  13: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/core/src/ops/function.rs:284:13
  14: std::panicking::try::do_call
             at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panicking.rs:524:40
  15: std::panicking::try
             at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panicking.rs:488:19
  16: std::panic::catch_unwind
             at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panic.rs:142:14
  17: std::rt::lang_start_internal::{{closure}}
             at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/rt.rs:148:48
  18: std::panicking::try::do_call
             at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panicking.rs:524:40
  19: std::panicking::try
             at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panicking.rs:488:19
  20: std::panic::catch_unwind
             at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panic.rs:142:14
  21: std::rt::lang_start_internal
             at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/rt.rs:148:20
  22: _main
  23: <unknown>
Error: Genesis is not needed (either Postgres DB or tree's Rocks DB is not empty)`

**Comment by ChengYueJia** [comment]
hi, @devudilip , maybe you can remove all cache to retry it.

**Comment by devudilip** [comment]
I tried with the new setup but it is still the same issue.
I have updated my code as well

**Comment by ChengYueJia** [comment]
hi, all. I've found out the reason behind this:

### Reason behind
As error logs(as below) shows,  the error is that L1 verifier key(generate by contract) does not match the one in the config(contract.toml).
#### L1 verifier key :
https://github.com/matter-labs/zksync-era/blob/998c455199d715d3a338f7641e241415dd3f1776/docs/guides/advanced/prover_keys.md#L61-L71

### Dig out more
As the explanation of `L1 verifier key`, var `SNARK_WRAPPER_VK_HASH` in `contract.toml` is influenced by the one in contract (https://github.com/matter-labs/era-contracts/blob/99cbf80a8633a3dfba62adbd3ca09adbddfcbccb/l1-contracts/contracts/zksync/Verifier.sol).


### Conclusion
So when the error appeared, it shows the zksync's commit is not adoptable with contract's.
And it's modified quite frequently recently.

So we can solve it by use the correct `contract's rev`(eg, reclone)

### Error logs

```bash
thread 'main' panicked at /mnt/paul/zksync-era/core/lib/zksync_core/src/lib.rs:144:13:
assertion `left == right` failed: L1 verifier key does not match the one in the config
  left: 0x750d8e21be7555a6841472a5cacd24c75a7ceb34261aea61e72bb7423a7d30fc
 right: 0x8574e152c41dc39a2ecab984545e1cf21cb3ec250b919018a8053f2fa270784f
stack backtrace:
```
