### ISSUE TITLE
Bridge Page Error

### ISSUE THREAD

**Issue by residenthiago2011** [matter-labs/zksync-era#99]
![image](https://github.com/matter-labs/zksync-era/assets/40614192/b56102f7-f6a8-4345-98d3-27b821ee8849)

I've Received the Following Error on the Bridge Page.

i Know it's Not the Right Place to Open a Issue for a Frontend Related Error, But it was the Only Way i Find out to Open a Issue Report, Since theres not a Repository for the zkSync Bridge App.

**Comment by hatemosphere** [comment]
correct place to ask such questions would be our Discord. please refer to docs to join our server.
