### ISSUE TITLE
Unfortunately kick out me in discord 

### ISSUE THREAD

**Issue by ashik0121** [matter-labs/zksync-era#994]
I don't know why I got kicked out of Discord plz help

**Comment by shreyassharmaa** [comment]
I also cant join discord through official invite link

**Comment by 0xsisyfos** [comment]
Hello,

Thank you for reaching out to us. 
Make sure you have a profile picture in Discord
Make sure you do not have words such as "admin", "airdrop", etc. in your profile name.
If you were banned, please fill out the form and we'll review as soon as we can https://appeal.zksync.dev/.

Best regards,

**Comment by hdiass** [comment]
Have same issue

**Comment by bxpana** [comment]
@ashik0121 @shreyassharmaa @hdiass @EmilLuta 

Please email us at support@zksync.io and we can help you there.
